controller_manager:
  ros__parameters:
    update_rate: 100
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    head_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: hsrb_gripper_controller/HrhGripperController
    omni_base_controller:
      type: hsrb_base_controllers/OmniBaseController
    servo_diagnostic_broadcaster:
      type: hsrb_diagnostic_broadcaster/ServoDiagnosticBroadcaster

hsrb_hw:
  ros__parameters:
    rs485_device: /dev/ttyCTI2
    use_usb: false
    network_timeout: 2000000
    network_tick: 10000

head_trajectory_controller:
  ros__parameters:
    joints:
      - head_tilt_joint
      - head_pan_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 0.05
      head_tilt_joint:
        goal: 0.2
    open_loop_control: true

arm_trajectory_controller:
  ros__parameters:
    joints:
      - arm_lift_joint
      - arm_flex_joint
      - arm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    constraints:
      stopped_velocity_tolerance: 0.5
      goal_time: 0.05
    open_loop_control: true

gripper_controller:
  ros__parameters:
    joints:
      - hand_motor_joint
    force_calib_data_path: /etc/opt/tmc/robot/conf.d/calib_results/hand_force_params.yaml
    position_goal_tolerance: 0.2
    left_spring_joint: hand_l_spring_proximal_joint
    right_spring_joint: hand_r_spring_proximal_joint
    open_loop_control: true

omni_base_controller:
  ros__parameters:
    joints:
      l_wheel: base_l_drive_wheel_joint
      r_wheel: base_r_drive_wheel_joint
      steer: base_roll_joint
    wheel_odom_map_frame: odom
    wheel_odom_base_frame: base_footprint_wheel
    odometry_publish_rate: 50.0
    transform_publish_rate: 50.0
    yaw_velocity_limit: 1.8
    wheel_velocity_limit: 8.5
    base_coordinates: [odom_x, odom_y, odom_t]
    odom_x: {p_gain: 1.0}
    odom_y: {p_gain: 1.0}
    odom_t: {p_gain: 1.0}
    constraints:
      stopped_velocity_tolerance: 0.0
      odom_x: {trajectory: 0.05}
      odom_y: {trajectory: 0.05}
      odom_t: {trajectory: 0.1}
    open_loop_control: true

