power_ecu_main_loop:
  ros__parameters:
    device: /dev/ttyCTI3
    port_receive_timeout_ms: 0.5
    battery_state/publish_rate: 1.0
    battery_charging/publish_rate: 10.0
    base_f_bumper_sensor/publish_rate: 10.0
    base_b_bumper_sensor/publish_rate: 10.0
    emergency_stop_button/publish_rate: 10.0
    imu/data/publish_rate: 100.0
    wireless_stop_button/publish_rate: 10.0
    wireless_stop_enable/publish_rate: 10.0
    runstop_button/publish_rate: 10.0