/**:
  ros__parameters:
    joint_state_update_delay_from_last_command: 0.5
    time_from_start: 0.1
    joint_trajectory_controllers:
      - arm_trajectory_controller
      - head_trajectory_controller
      - gripper_controller
    gripper_controller:
      joints: ['hand_motor_joint']
    max_velocity_joint_names:
      - head_pan_joint
      - head_tilt_joint
      - base_l_passive_wheel_y_joint
      - base_l_drive_wheel_joint
      - base_l_passive_wheel_x_joint
      - torso_lift_joint
      - base_r_passive_wheel_x_joint
      - wrist_roll_joint
      - base_l_passive_wheel_z_joint
      - base_r_passive_wheel_y_joint
      - arm_lift_joint
      - base_r_passive_wheel_z_joint
      - left_proximal_joint
      - arm_flex_joint
      - hand_r_distal_joint
      - right_proximal_joint
      - hand_l_distal_joint
      - wrist_flex_joint
      - base_r_drive_wheel_joint
      - arm_roll_joint
      - base_roll_joint
      - hand_motor_joint
    max_velocity:
      - 0.8
      - 0.6
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.8
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.2
      - 0.4
      - 0.2
      - 0.2
      - 0.2
      - 0.6
      - 0.2
      - 0.6
      - 0.2
      - 0.5
