<package format="3">
  <name>hsrb_align</name>
  <version>3.0.0</version>
  <description>Initial pose scripts for HSR-B</description>

  <maintainer email="xr-hsr-support@mail.toyota.co.jp">HSR Support</maintainer>

  <license>BSD 3-clause Clear License</license>
  <depend>tmc_safe_pose_changer</depend>
  <depend>hsrb_angle_sensors_alignment</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>